 const CART_ACTION_TYPE = {
	TOGGLE_CART_HIDDEN :  "TOGGLE_CART_HIDDEN",
	ADD_FOOD_TO_CART : "ADD_FOOD_TO_CART",
	DESCREASE_FOOD_TO_CART : "DESCREASE_FOOD_TO_CART",
	DELETE_FOOD_TO_CART :  "DELETE_FOOD_TO_CART",
	REMOVE_FOOD_TO_CART:  "REMOVE_FOOD_TO_CART"
}

export default  CART_ACTION_TYPE;